version: "3.3"

services:
  tor:
    image: goldy/tor-hidden-service:0.3.5.8
    network_mode: "host"
    environment:
        SERVICE1_TOR_SERVICE_HOSTS: 80:localhost:7000
        SERVICE1_TOR_SERVICE_VERSION: '3'
  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 7000:7000
    ulimits:
      nproc: 65535
      nofile:
        soft: 10000
        hard: 10000
  db_p:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
  proxysql:
    network_mode: "host"
    volumes:
      - "./proxysql.cnf:/etc/proxysql.cnf"
    image: proxysql/proxysql
volumes:
  db: {}
